/**
 * 400 curated search terms optimized for capturing remaining 2025 TCAD properties.
 *
 * Selection criteria:
 *   - All terms >= 4 characters (MIN_TERM_LENGTH)
 *   - No duplicates with batch-configs.ts or backfill-2025.ts STATIC_TERMS
 *   - No term is a prefix of another term in this list (avoids superset waste)
 *   - Prioritized by expected Travis County property yield
 *
 * Runtime dedup: backfill scripts apply getSearchedTermSets() and
 * isSupersetOfAny() to skip already-searched or redundant terms.
 *
 * Usage: folded into the search-term inventory via batch-configs.ts (the
 * "backfill-2025-source" entry consumed by utils/list-all-search-terms.ts) —
 * there is no enqueue pipeline for batch types — or import
 * BACKFILL_2025_SOURCE_TERMS directly.
 */

export const BACKFILL_2025_SOURCE_TERMS: readonly string[] = [
	// ── Common US surnames (Census top 200-500, not in existing configs) ─

	"King",
	"Hall",
	"Long",
	"Ross",
	"Freeman",
	"Harvey",
	"Webb",
	"Nichols",
	"Murray",
	"Knight",
	"Duncan",
	"Cunningham",
	"Ferguson",
	"Gordon",
	"Rice",
	"Porter",
	"Hunter",
	"Boyd",
	"Arnold",
	"Wagner",
	"Rose",
	"Black",
	"Grant",
	"Warner",
	"Garrett",
	"Hawkins",
	"Banks",
	"Fields",
	"Daniels",
	"Chandler",
	"Maxwell",
	"Tucker",
	"Byrd",
	"Hardy",
	"Cross",
	"Garner",
	"Brady",
	"Barker",
	"Norris",
	"Briggs",
	"Brock",
	"Holt",
	"Sparks",
	"Mack",
	"Walton",
	"Dawson",
	"Gibbs",
	"Lambert",
	"Santiago",
	"Willis",
	"Potter",
	"Hale",
	"Swanson",
	"Sharp",
	"Mann",
	"Bowen",
	"Yates",
	"Davidson",
	"French",
	"Neal",
	"Marsh",
	"Burke",
	"Graves",
	"Mccoy",
	"Benson",
	"Snyder",
	"Hoffman",
	"Keller",
	"Pearson",
	"Newton",
	"Jennings",
	"Thornton",
	"Watts",
	"Goodwin",
	"Dalton",
	"Shields",
	"Poole",
	"Lowe",
	"Bauer",
	"Summers",
	"Conway",
	"Whitaker",
	"Grimes",
	"Horn",
	"Wise",
	"Gill",
	"Barber",
	"Cummings",
	"Brennan",
	"Sims",
	"Phelps",
	"Pollard",
	"Whitfield",
	"Rowland",
	"Underwood",
	"Stafford",
	"Moody",
	"Moran",
	"Woodard",
	"Dickson",
	"Combs",
	"Prince",
	"Stout",
	"Tripp",
	"Cooke",
	"Pitts",
	"Russo",
	"Stark",
	"Stokes",
	"Vaughn",
	"Werner",
	"York",
	"Hines",
	"Downs",
	"Blount",
	"Adkins",
	"Pruitt",
	"Mcdaniel",
	"Glover",
	"Roth",
	"Odom",
	"Roach",

	// ── Hispanic/Latino surnames (Travis County high density) ────────────

	"Valencia",
	"Figueroa",
	"Montoya",
	"Pacheco",
	"Trujillo",
	"Dominguez",
	"Espinoza",
	"Calderon",
	"Cisneros",
	"Bautista",
	"Camacho",
	"Cardenas",
	"Carrillo",
	"Gallegos",
	"Valenzuela",
	"Galvan",
	"Escobedo",
	"Villarreal",
	"Villegas",
	"Velasquez",
	"Mercado",
	"Arellano",
	"Becerra",
	"Beltran",
	"Jaramillo",
	"Guardado",
	"Ibarra",
	"Huerta",
	"Renteria",
	"Balderas",
	"Coronado",
	"Sandoval",
	"Rangel",
	"Zuniga",
	"Cantu",
	"Garza",
	"Trevino",
	"De Leon",
	"Elizondo",
	"Quintero",
	"Lucero",
	"Esquivel",
	"Ochoa",
	"Montes",
	"Cabrera",
	"Portillo",
	"Villalobos",
	"Magana",
	"Gallardo",
	"Barrientos",
	"Zamora",
	"Trejo",
	"Orozco",
	"Arroyo",
	"Macias",
	"Enriquez",
	"Deanda",
	"Lozano",
	"Navarrete",
	"Bustamante",
	"Hinojosa",
	"Rubio",
	"Salinas",
	"Olivares",
	"Cortez",
	"Olvera",
	"Saldana",
	"Moreno",
	"Navarro",
	"Peralta",
	"Quiroz",
	"Tejeda",
	"Urena",
	"Yanez",

	// ── Asian surnames (growing Travis County population) ────────────────

	"Pham",
	"Tran",
	"Gupta",
	"Shah",
	"Singh",
	"Khan",
	"Chen",
	"Wang",
	"Yang",
	"Choi",
	"Shin",
	"Yoon",
	"Tanaka",
	"Nakamura",
	"Suzuki",
	"Iyer",
	"Agarwal",
	"Saxena",
	"Chopra",
	"Malik",
	"Ling",
	"Deng",
	"Zhou",
	"Bose",
	"Nair",
	"Rana",
	"Syed",
	"Ahmed",
	"Abbas",
	"Mirza",

	// ── Austin-area street names (match property_address field) ──────────

	"Congress",
	"Guadalupe",
	"Burnet",
	"Cameron",
	"Metric",
	"Parmer",
	"Riverside",
	"Exposition",
	"Shoal Creek",
	"Research",
	"Duval",
	"Speedway",
	"Nueces",
	"Lavaca",
	"Brazos",
	"Trinity",
	"Cesar Chavez",
	"Barton Springs",
	"Enfield",
	"Woodward",
	"Grover",
	"Menchaca",
	"Brodie",
	"Escarpment",
	"Convict Hill",
	"Slaughter Creek",
	"Spicewood Springs",
	"Jollyville",
	"Riata",
	"Stonelake",
	"Great Hills",
	"Balcones Woods",
	"Ridgeline",
	"Westbank",
	"Westgate",
	"Steck",
	"Koenig",
	"Airport",
	"McNeil",

	// ── Austin subdivisions and neighborhoods ───────────────────────────

	"Avana",
	"Avery Ranch",
	"Bella Vista",
	"Canyon Creek",
	"Circle C Ranch",
	"Crystal Falls",
	"Davis Spring",
	"Davenport Ranch",
	"Fairview",
	"Forest Creek",
	"Fern Bluff",
	"Garrison Park",
	"Gateway",
	"Glenwood",
	"Grande Vista",
	"Heritage Oaks",
	"Indian Hills",
	"Jester Estates",
	"Lago Vista",
	"Legend Oaks",
	"Milwood",
	"North Creek",
	"Oak Knoll",
	"Parkside",
	"Plum Creek",
	"Preserve",
	"River Place",
	"Rob Roy",
	"Scofield",
	"Sendera",
	"Shadow Creek",
	"Sierra Vista",
	"Silver Creek",
	"Star Ranch",
	"Stone Canyon",
	"Sweetwater",
	"Teravista",
	"Travis Oaks",
	"Twin Creeks",
	"Walsh Ranch",
	"Westcreek",
	"Wolf Ranch",
	"Sendero Hills",
	"Garrison Oaks",
	"Circle S",

	// ── Property description and building keywords ──────────────────────

	"Condo",
	"Townhouse",
	"Apartment",
	"Duplex",
	"Triplex",
	"Fourplex",
	"Mobile Home",
	"Manufactured",
	"Single Family",
	"Multi Family",
	"Mixed Use",
	"Vacant Lot",
	"Tract",
	"Subdivision",
	"Townhome",
	"Senior Living",
	"Assisted Living",
	"Retirement",
	"Student Housing",
	"Storage",

	// ── Entity/business terms not yet covered ───────────────────────────

	"Survivor",
	"Executor",
	"Heir",
	"Guardian",
	"Receivership",
	"Bankrupt",
	"Foreclosure",
	"Lien",
	"Homestead",
	"Church",
	"Baptist",
	"Methodist",
	"Catholic",
	"Presbyterian",
	"Lutheran",
	"Episcopal",
	"Temple",
	"Synagogue",
	"Ministry",
	"Tabernacle",
	"Community Church",
	"School District",
	"University",
	"Academy",
	"Hospital",
	"Medical",
	"Clinic",
	"Dental",
	"Veterinary",
	"Pharmacy",

	// ── Additional geographic and suburb terms ──────────────────────────

	"Georgetown",
	"Hutto",
	"Elgin",
	"Manor",
	"Del Valle",
	"Bastrop",
	"Wimberley",
	"Kyle",
	"San Marcos",
	"New Braunfels",
	"Lockhart",
	"Marble Falls",
	"Jonestown",
	"Volente",
	"Point Venture",
	"Horseshoe Bay",
	"Liberty Hill",
	"Dripping",
	"Manchaca Road",
	"South First",

	// ── Multi-word high-value compound terms ─────────────────────────────

	"Wells Fargo",
	"Bank of America",
	"Chase",
	"Citibank",
	"Federal",
	"National Bank",
	"Credit Union",
	"Savings",
	"Insurance",
	"Mortgage Company",
	"Title Company",
	"Land Trust",
	"Tax Sale",
	"Sheriff Sale",
	"County",
	"State of Texas",
	"City of Austin",
	"Travis County",
	"Williamson",
	"Hays County",
];
