/**
 * Static high-yield terms for the 2025 backfill strategy.
 *
 * Selection criteria:
 *   - All terms >= 4 characters (MIN_TERM_LENGTH)
 *   - No duplicates within this list
 *   - Disjoint from BACKFILL_2025_SOURCE_TERMS and BATCH_CONFIGS
 *     (each term lives in exactly one list; verify with utils/list-curated-terms.ts,
 *     whose `duplicated` bucket must stay empty)
 *
 * Usage: imported by scripts/backfill-2025.ts as the STATIC_TERMS source.
 */

export const BACKFILL_2025_STATIC_TERMS: readonly string[] = [
  // First names
  "Michael",
  "Christopher",
  "Paul",
  "Patrick",
  "Jerry",
  "Tyler",
  "Aaron",
  "Peter",
  "Nathan",
  "Arthur",
  "Roger",
  "Eugene",
  "Roy",
  "Ralph",
  "Randy",
  "Jennifer",
  "Jessica",
  "Amanda",
  "Melissa",
  "Michelle",
  "Stephanie",
  "Nicole",
  "Angela",
  "Christina",
  "Samantha",
  "Katherine",
  "Christine",
  "Deborah",
  "Rachel",
  "Laura",
  "Carolyn",
  "Janet",
  "Catherine",
  "Frances",
  "Joyce",
  "Diane",
  "Alice",
  "Julie",
  "Heather",
  "Teresa",
  "Gloria",
  "Evelyn",
  "Cheryl",
  "Mildred",
  "Martha",
  "Donna",
  "Dorothy",
  "Sharon",
  "Betty",
  "Helen",
  "Sandra",
  "Kimberly",
  "Emily",
  "Brenda",
  "Amy",
  "Anna",
  "Rebecca",
  "Virginia",
  "Pamela",
  "Cynthia",
  "Ruth",
  "Kathleen",
  "Linda",
  "Nancy",
  "Karen",
  "Margaret",
  "Marie",
  "Frank",
  "Jack",
  "Dennis",
  "Henry",
  "Douglas",
  "Gerald",
  "Lawrence",
  "Bruce",
  "Louis",
  "Philip",
  "Johnny",
  "Harry",
  "Vincent",
  "Billy",
  "Carl",
  "Terry",
  "Sean",
  "Austin",
  "Jesse",
  "Ethan",
  "Dylan",
  "Bryan",
  "Jordan",
  "Miguel",
  "Carlos",
  "Rafael",
  "Angel",
  "Oscar",
  "Fernando",
  "Manuel",
  "Ricardo",
  "Roberto",
  "Eduardo",
  "Pedro",
  "Alejandro",
  "Sergio",
  // Last names
  "Jenkins",
  "Perry",
  "Powell",
  "Patterson",
  "Washington",
  "Butler",
  "Simmons",
  "Foster",
  "Gonzales",
  "Bryant",
  "Alexander",
  "Russell",
  "Griffin",
  "Hayes",
  "Myers",
  "Hamilton",
  "Graham",
  "Sullivan",
  "Wallace",
  "Woods",
  "Cole",
  "West",
  "Owens",
  "Reynolds",
  "Fisher",
  "Ellis",
  "Harrison",
  "Gibson",
  "McDonald",
  "Marshall",
  "Ortega",
  "Burns",
  "Kelley",
  "Dunn",
  "Crawford",
  "Vasquez",
  "Dean",
  "Lane",
  "Soto",
  "Lynch",
  "Stone",
  "Dixon",
  "Hicks",
  "Weaver",
  "Hart",
  "Hunt",
  "Palmer",
  "Robertson",
  "Holmes",
  "Spencer",
  "Francis",
  "Stephens",
  "Vargas",
  "Herrera",
  "Medina",
  "Aguilar",
  "Salazar",
  "Delgado",
  "Vega",
  "Rios",
  "Romero",
  "Guerrero",
  "Castro",
  "Estrada",
  "Contreras",
  "Fuentes",
  "Leon",
  "Acosta",
  "Maldonado",
  "Rosales",
  "Barnes",
  "Coleman",
  "Cox",
  "Ward",
  // Geo/street/neighborhood
  "Slaughter",
  "Lamar",
  "Manchaca",
  "Round Rock",
  "Cedar Park",
  "Pflugerville",
  "Lakeway",
  "Woodland",
  "Greenwood",
  "Sunset",
  "Wells Branch",
  "Ben White",
  "Dessau",
  "Steiner",
  "Avery",
  "Circle C",
  "Dripping Springs",
  "Onion Creek",
  "Shady Hollow",
  "Travis Country",
  "Barton Creek",
  "Westover",
  "Bryker Woods",
  "North Loop",
  "South Congress",
  "East Riverside",
  "South Lamar",
  "North Austin",
  "Bee Cave",
  "Lakeline",
  "Brushy Creek",
  "Leander",
  "Highland",
  "Clarksville",
  "Old West Austin",
  "Bouldin Creek",
  "Travis Heights",
  "South Austin",
  "North Lamar",
  "East Austin",
  "Anderson Mill",
  "Braker",
  "Rundberg",
  "Oltorf",
  "Stassney",
  "William Cannon",
  "Buda",
  // Entity/business
  "Ventures",
  "Services",
  "Solutions",
  "International",
  "National",
  "Resources",
  "Global",
  "Enterprises",
  "Partners",
  "Advisors",
  "Consulting",
  "Management",
  "Alliance",
  "Network",
  "Labs",
  "Studio",
  "Works",
  "Builders",
  "Communities",
  "Rentals",
  "Housing",
  "Leasing",
  "Mortgage",
  // Geo features
  "Bend",
  "Trace",
  "Crossing",
  "Circle",
  "Court",
  "Place",
  "Hollow",
  "Branch",
  "Pass",
  "Point",
  "Island",
  "Terrace",
  "Cedar",
  "Pine",
  "Cypress",
  "Willow",
  "Birch",
  "Holly",
  "Sage",
  "Laurel",
  "Magnolia",
  "Pecan",
  "Mesquite",
  "Live Oak",
  "Post Oak",
  "Oaks",
  "Pines",
  "Hills",
  "Springs",
  "Falls",
  "Shores",
  "Estates",
  "Landing",
  "Overlook",
  "Retreat",
  "Haven",
  "Commons",
  "Gardens",
  "Heights",
  "Pointe",
];
