/**
 * Centralized batch enqueue configurations.
 * Each config defines terms for a specific search category.
 *
 * Priority scale (BullMQ convention: lower number = higher priority):
 *   -100  ultra-high-priority (processed first)
 *      1  high-priority, priority-terms
 *      2  corporation
 *   omit  standard priority (all others)
 *
 * Usage: npx tsx scripts/enqueue-batch.ts <batchType>
 * Example: npx tsx scripts/enqueue-batch.ts llc
 */

import type { BatchEnqueueConfig } from "../lib/queue-utils";

type BatchConfigEntry = Omit<BatchEnqueueConfig, "extraLogs"> & {
	extraLogs?: () => void;
};

export const BATCH_CONFIGS: Record<string, BatchConfigEntry> = {
	llc: {
		batchName: "LLC",
		emoji: "🏭",
		terms: [
			"LLC",
			"LLC.",
			"L.L.C.",
			"Limited Liability",
			"LMTD",
			"Limit",
			"L L C",
			"LTD",
			"Co LLC",
		],
		userId: "llc-batch-enqueue",
	},

	trust: {
		batchName: "Trust & Estate",
		emoji: "📜",
		terms: [
			"Trust",
			"Trustee",
			"Estate",
			"Family Trust",
			"Revocable Trust",
			"Irrevocable Trust",
			"Living Trust",
			"Testamentary",
			"Fiduciary",
			"Beneficiary",
		],
		userId: "trust-batch-enqueue",
	},

	corporation: {
		batchName: "Corporation",
		emoji: "🏛️",
		terms: [
			"Corp",
			"Corp.",
			"Corporation",
			"Incorporated",
			"Inc",
			"Inc.",
			"Company",
			"Co.",
			"Enterprise",
			"Enterprises",
		],
		userId: "corporation-batch-enqueue",
		priority: 2,
	},

	commercial: {
		batchName: "Commercial",
		emoji: "🏢",
		terms: [
			"Shopping",
			"Retail",
			"Office",
			"Warehouse",
			"Industrial",
			"Commercial",
			"Business",
			"Store",
			"Mall",
			"Building",
		],
		userId: "commercial-batch-enqueue",
	},

	construction: {
		batchName: "Construction",
		emoji: "🏗️",
		terms: [
			"Construction",
			"Builders",
			"Builder",
			"Contractor",
			"Contracting",
			"Homes",
			"Home",
			"Custom Homes",
			"Housing",
			"Residential Builders",
		],
		userId: "construction-batch-enqueue",
	},

	foundation: {
		batchName: "Foundation",
		emoji: "🎗️",
		terms: [
			"Foundation",
			"Charitable",
			"Charity",
			"Nonprofit",
			"Non-Profit",
			"Organization",
			"Institute",
			"Society",
			"Endowment",
		],
		userId: "foundation-batch-enqueue",
	},

	partnership: {
		batchName: "Partnership",
		emoji: "🤝",
		terms: [
			"Partnership",
			"Partners",
			"Part",
			"LP",
			"LLP",
			"Association",
			"Associates",
			"Assoc",
			"Assoc.",
			"Joint Venture",
		],
		userId: "partnership-batch-enqueue",
	},

	investment: {
		batchName: "Investment",
		emoji: "💰",
		terms: [
			"Investments",
			"Holdings",
			"Capital",
			"Fund",
			"Equity",
			"Ventures",
			"Asset",
			"Portfolio",
			"Management",
			"Manage",
		],
		userId: "investment-batch-enqueue",
	},

	"property-type": {
		batchName: "Property Type",
		emoji: "🏘️",
		terms: [
			"Properties",
			"Property",
			"Real Estate",
			"Realty",
			"Land",
			"Acres",
			"Development",
			"Developers",
			"Plaza",
			"Center",
		],
		userId: "property-type-batch-enqueue",
	},

	residential: {
		batchName: "Residential",
		emoji: "🏠",
		terms: [
			"Smith",
			"Johnson",
			"Williams",
			"Brown",
			"Jones",
			"Miller",
			"Davis",
			"Garcia",
			"Rodriguez",
			"Wilson",
		],
		userId: "residential-batch-enqueue",
	},

	grove: {
		batchName: "Grove",
		emoji: "🌳",
		terms: ["Grove"],
		userId: "grove-batch-enqueue",
	},

	"high-priority": {
		batchName: "High Priority Streets & Names",
		emoji: "🔥",
		terms: ["Boulevard", "Way", "Terrace", "Michelle"],
		userId: "high-priority-batch-enqueue",
		priority: 1,
	},

	"priority-terms": {
		batchName: "Priority Geographic & Entity",
		emoji: "🎯",
		terms: ["Lake", "River", "Pecan", "Maple", "Oak", "Mount", "Limited"],
		userId: "priority-terms-batch-enqueue",
		priority: 1,
	},

	"ultra-high-priority": {
		batchName: "Ultra High Priority",
		emoji: "🚀",
		terms: [
			"Street",
			"Drive",
			"Lane",
			"Road",
			"Amy",
			"Cynthia",
			"Brook",
			"Meadow",
			"Valley",
			"Point",
		],
		userId: "ultra-high-priority-batch-enqueue",
		priority: -100,
	},

	"hispanic-surnames": {
		batchName: "Hispanic Surnames",
		emoji: "🌎",
		terms: [
			"Acuna",
			"Adame",
			"Anaya",
			"Avila",
			"Baeza",
			"Banda",
			"Bello",
			"Bosco",
			"Bravo",
			"Bueno",
			"Calvo",
			"Campo",
			"Casas",
			"Cerda",
			"Chapa",
			"Coria",
			"Corzo",
			"Duran",
			"Garzo",
			"Lerma",
			"Llano",
			"Loera",
			"Lujan",
			"Mares",
			"Marin",
			"Mejia",
			"Mendo",
			"Milla",
			"Monje",
			"Nieto",
			"Oliva",
			"Ozuna",
			"Parra",
			"Ponce",
			"Reyna",
			"Rocha",
			"Rojas",
			"Roque",
			"Saenz",
			"Serna",
			"Tamez",
			"Tello",
			"Tovar",
			"Uribe",
			"Valde",
			"Valez",
			"Viera",
		],
		userId: "hispanic-surnames-batch-enqueue",
	},

	"indian-surnames": {
		batchName: "Indian Surnames",
		emoji: "🌏",
		terms: [
			"Bajaj",
			"Bhatt",
			"Batra",
			"Dixit",
			"Joshi",
			"Kapur",
			"Kumar",
			"Mehta",
			"Mehra",
			"Misra",
			"Nagar",
			"Naidu",
			"Nanda",
			"Pande",
			"Reddy",
			"Sethi",
			"Sinha",
			"Sodhi",
			"Verma",
			"Yadav",
		],
		userId: "indian-surnames-batch-enqueue",
	},

	"asian-surnames": {
		batchName: "Asian Surnames",
		emoji: "🌏",
		terms: ["Chang", "Hsiao", "Huang", "Hwang", "Jiang", "Liang", "Tsang"],
		userId: "asian-surnames-batch-enqueue",
	},

	"curated-first-names": {
		batchName: "Curated First Names",
		emoji: "👤",
		terms: [
			"Annie",
			"Anton",
			"Anuja",
			"April",
			"Arely",
			"Ariel",
			"Arjun",
			"Baldo",
			"Belen",
			"Belma",
			"Berto",
			"Betsy",
			"Bonny",
			"Boris",
			"Brisa",
			"Buddy",
			"Caleb",
			"Candy",
			"Carla",
			"Casey",
			"Cathy",
			"Cecil",
			"Celia",
			"Chava",
			"Chloe",
			"Chris",
			"Chuck",
			"Cielo",
			"Cindy",
			"Clara",
			"Clare",
			"Clint",
			"Clyde",
			"Corey",
			"Cyril",
			"Cyrus",
			"Dalia",
			"Damon",
			"Danny",
			"Dante",
			"Daren",
			"Darla",
			"Darcy",
			"Daryl",
			"Debby",
			"Deepa",
			"Deion",
			"Della",
			"Delia",
			"Denis",
			"Derek",
			"Devin",
			"Devon",
			"Dewey",
			"Diego",
			"Dolly",
			"Donna",
			"Doris",
			"Drake",
			"Dulce",
			"Dusty",
			"Dwain",
			"Dylan",
			"Earle",
			"Ebony",
			"Eddie",
			"Edgar",
			"Edwin",
			"Efren",
			"Eldon",
			"Elena",
			"Elisa",
			"Elise",
			"Ellie",
			"Elsie",
			"Elton",
			"Elvis",
			"Emery",
			"Emile",
			"Emily",
			"Erica",
			"Ernie",
			"Ervin",
			"Essie",
			"Ethan",
			"Ethel",
			"Faith",
			"Fanny",
			"Felix",
			"Fidel",
			"Fiona",
			"Floyd",
			"Flynn",
			"Frank",
			"Fritz",
			"Frida",
			"Garry",
			"Gavin",
			"Gemma",
			"Gerri",
			"Ginny",
			"Glenn",
			"Gopal",
			"Grace",
			"Greta",
			"Gregg",
			"Haley",
			"Hanna",
			"Hazel",
			"Heath",
			"Heidi",
			"Helen",
			"Henry",
			"Holly",
			"Homer",
			"Huber",
			"Ilene",
			"Irene",
			"Ivory",
			"Isaac",
			"Isael",
			"Jaime",
			"Janie",
			"Janet",
			"Janis",
			"Jared",
			"Jason",
			"Jenna",
			"Jenny",
			"Jesse",
			"Jewel",
			"Jimmy",
			"Johan",
			"Jonas",
			"Jorge",
			"Josef",
			"Juana",
			"Jules",
			"Julia",
			"Julie",
			"Jyoti",
			"Karen",
			"Karin",
			"Katie",
			"Kavya",
			"Kayla",
			"Keith",
			"Kelly",
			"Kenny",
			"Kevin",
			"Kirby",
			"Klaus",
			"Lacey",
			"Laila",
			"Lance",
			"Larry",
			"Layne",
			"Leigh",
			"Lenny",
			"Leroy",
			"Lilly",
			"Linda",
			"Linus",
			"Logan",
			"Lonny",
			"Loren",
			"Lorna",
			"Louis",
			"Lucas",
			"Lucia",
			"Luisa",
			"Luigi",
			"Lydia",
			"Lynda",
			"Mabel",
			"Macie",
			"Madge",
			"Mandy",
			"Manny",
			"Marco",
			"Marge",
			"Marie",
			"Mario",
			"Marla",
			"Mason",
			"Mateo",
			"Maude",
			"Maura",
			"Meena",
			"Megan",
			"Mercy",
			"Merry",
			"Midge",
			"Miley",
			"Miles",
			"Mindy",
			"Mirna",
			"Misty",
			"Mitch",
			"Mohan",
			"Moira",
			"Molly",
			"Monte",
			"Monty",
			"Moses",
			"Myrna",
			"Nabil",
			"Nadia",
			"Nancy",
			"Naomi",
			"Nelly",
			"Nesta",
			"Nigel",
			"Nicky",
			"Nikki",
			"Nilda",
			"Nisha",
			"Nitin",
			"Nolan",
			"Norma",
			"Olive",
			"Oscar",
			"Pablo",
			"Paige",
			"Pansy",
			"Patsy",
			"Patty",
			"Paula",
			"Pavan",
			"Pearl",
			"Pedro",
			"Peggy",
			"Penny",
			"Percy",
			"Perry",
			"Peter",
			"Pooja",
			"Polly",
			"Priya",
			"Queen",
			"Radha",
			"Randi",
			"Randy",
			"Raoul",
			"Raven",
			"Reece",
			"Reema",
			"Reina",
			"Renee",
			"Rhoda",
			"Ricky",
			"Riley",
			"Robin",
			"Rocio",
			"Rocky",
			"Roger",
			"Roman",
			"Ronda",
			"Rosie",
			"Rowan",
			"Roxie",
			"Royal",
			"Rufus",
			"Rusty",
			"Sadie",
			"Sagar",
			"Sally",
			"Sandy",
			"Sarah",
			"Scott",
			"Seema",
			"Selma",
			"Serge",
			"Shane",
			"Shana",
			"Shari",
			"Shawn",
			"Sheri",
			"Simon",
			"Sonia",
			"Sonja",
			"Sonya",
			"Sonny",
			"Stacy",
			"Starr",
			"Steve",
			"Sunil",
			"Suraj",
			"Susie",
			"Swati",
			"Tammy",
			"Tamra",
			"Tanya",
			"Tasha",
			"Teddy",
			"Terri",
			"Terry",
			"Tessa",
			"Theda",
			"Tiana",
			"Tisha",
			"Titus",
			"Tommy",
			"Tonya",
			"Trace",
			"Trent",
			"Trish",
			"Trudy",
			"Tyler",
			"Tyson",
			"Vance",
			"Varun",
			"Vicki",
			"Vidal",
			"Vijay",
			"Vikki",
			"Vince",
			"Viola",
			"Vivek",
			"Wally",
			"Wanda",
			"Wayne",
			"Wendy",
			"Wyatt",
			"Wylie",
			"Zelda",
			"Zelma",
		],
		userId: "curated-first-names-batch-enqueue",
	},
};

/**
 * Terms with >5000 max_results that should be split into narrower sub-queries
 * to prevent truncation and timeouts. Based on search_term_analytics data.
 */
export const HIGH_RESULT_TERM_SPLITS: ReadonlyMap<string, readonly string[]> =
	new Map([
		// Oak (7210 max_results) → neighborhood/subdivision sub-queries
		["Oak", ["Oak Hill", "Oakwood", "Oak Run", "Oakhurst", "Oak Creek"]],
		// Maria (6026 max_results) → common middle-initial sub-queries
		["Maria", ["Maria E", "Maria G", "Maria R", "Maria L"]],
		// Estate (5051 max_results) → specific entity patterns
		["Estate", ["Estate of", "Estates at", "Estate Trust"]],
	]);

export function getAvailableBatchTypes(): string[] {
	return Object.keys(BATCH_CONFIGS);
}
