module.exports = {
  apps: [
    {
      name: 'tcad-api',
      script: './scripts/start.sh',
      cwd: '/home/aledlie/tcad-scraper/server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        HOST: '0.0.0.0',
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/tcad_scraper',
      },
      error_file: '/home/aledlie/tcad-scraper/server/logs/pm2-error.log',
      out_file: '/home/aledlie/tcad-scraper/server/logs/pm2-out.log',
      log_file: '/home/aledlie/tcad-scraper/server/logs/pm2-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'continuous-enqueue',
      script: 'doppler',
      args: 'run -- npx tsx src/scripts/continuous-batch-scraper.ts',
      cwd: '/home/aledlie/tcad-scraper/server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/tcad_scraper',
      },
      error_file: '/home/aledlie/tcad-scraper/server/logs/continuous-enqueue-error.log',
      out_file: '/home/aledlie/tcad-scraper/server/logs/continuous-enqueue-out.log',
      log_file: '/home/aledlie/tcad-scraper/server/logs/continuous-enqueue-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
  scraper: [
    {
      name: 'tcad-scraper',
      script: './scripts/start.sh',
      cwd: '/home/aledlie/tcad-scraper/server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4001,
        HOST: '0.0.0.0',
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/tcad_scraper',
      },
      error_file: '/home/aledlie/tcad-scraper/server/logs/scraper-error.log',
      out_file: '/home/aledlie/tcad-scraper/server/logs/scraper-out.log',
      log_file: '/home/aledlie/tcad-scraper/server/logs/scraper-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
  test : [
    {
      name: 'tcad-scraper',
      script: './scripts/start.sh',
      cwd: '/home/aledlie/tcad-scraper/server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'test',
        PORT: 5001,
        HOST: '0.0.0.0',
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/tcad_scraper',
      },
      error_file: '/home/aledlie/tcad-scraper/server/logs/scraper-error.log',
      out_file: '/home/aledlie/tcad-scraper/server/logs/scraper-out.log',
      log_file: '/home/aledlie/tcad-scraper/server/logs/scraper-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
};
